### ISSUE TITLE
Cant launch the app [Help!]

### ISSUE THREAD

**Issue by surajmandalcell** [mirkobrombin/ElementaryPython#8]
So i just cloned it and tried running the `com.github.mirkobrombin.elementarypython` but it threw this error. Then i tried to install using setup.py and run it still threw same error. Finally tried to launhcn using main.py and guess what, it didnt work. please help!

```
ElementaryPython on  master took 25s 
➜ com.github.mirkobrombin.elementarypython
/usr/lib/python3/dist-packages/gi/types.py:204: Warning: cannot derive 'elementarypython+main+Application' from non-derivable parent type 'void'
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "/usr/local/bin/com.github.mirkobrombin.elementarypython", line 35, in <module>
    import elementarypython.main
  File "/usr/local/bin/elementarypython/main.py", line 31, in <module>
    class Application(Granite.Application):
  File "/usr/lib/python3/dist-packages/gi/types.py", line 213, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 192, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 204, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create new GType: elementarypython+main+Application (subclass of void)
```

**Comment by mirkobrombin** [comment]
Have you installed all requirements?
python3
libgtk-3-dev
libgranite-dev

**Comment by surajmandalcell** [comment]
Yes :disappointed: 
```
libgtk-3-dev is already the newest version (3.22.30-1ubuntu1).
python3 is already the newest version (3.6.5-3).
libgranite-dev is already the newest version (0.5.1+r1182+pkg94~daily~ubuntu5.0.1).
```

**Comment by mirkobrombin** [comment]
Are you on elementary OS?
Try running the main.py without installing.

Il giorno dom 3 giu 2018 alle ore 02:49 Suraj Mandal <
notifications@github.com> ha scritto:

**Comment by mirkobrombin** [comment]
Are you on elementary OS?
Try running the main.py without installing.

`python3 main.py`

**Comment by surajmandalcell** [comment]
Yup, am running elementary os
Nope, it didn't work :cry: 
```sh
ElementaryPython/elementarypython on  master 
➜ python3 main.py
/usr/lib/python3/dist-packages/gi/types.py:204: Warning: cannot derive '__main__+Application' from non-derivable parent type 'void'
  _gi.type_register(cls, namespace.get('__gtype_name__'))
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    class Application(Granite.Application):
  File "/usr/lib/python3/dist-packages/gi/types.py", line 213, in __init__
    super(GObjectMeta, cls).__init__(name, bases, dict_)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 192, in __init__
    cls._type_register(cls.__dict__)
  File "/usr/lib/python3/dist-packages/gi/types.py", line 204, in _type_register
    _gi.type_register(cls, namespace.get('__gtype_name__'))
RuntimeError: could not create new GType: __main__+Application (subclass of void)
```

**Comment by mirkobrombin** [comment]
I think the problem is the daily repo. I'm using granite 0.4 not 0.5.

**Comment by surajmandalcell** [comment]
oh. any way to switch to granite 0.4?

**Comment by surajmandalcell** [comment]
or migrate the app to 0.5

**Comment by mirkobrombin** [comment]
I think that's the problem. Install the specific package, do a search with apt search.

**Comment by surajmandalcell** [comment]
I'm using eos daily builds, wont it cause problems?
I basically installed elementary os daily build  on top of ubuntu 18.04. Isn't there a way to migrate to granite 0.5?

**Comment by mirkobrombin** [comment]
Mmh in my elementary installation (not in daily) works fine. I can't do the switch now.

**Comment by mirkobrombin** [comment]
I confirm that it works with the latest stable release.
